### ISSUE TITLE
Unable to set Height Threshold

### ISSUE THREAD

**Issue by lmcancu1** [limengdu/MR60FDA2_ESPHome_external_components#5]
I am unable to set the Height Threshold. When I set it to anything other than 0.6m, it always defaults back to 0.6m. It rejects the new value

![Image](https://github.com/user-attachments/assets/01339718-9c53-49b5-8b77-0c6ff3d894e3)

![Image](https://github.com/user-attachments/assets/0e00c8dd-8f1d-4875-bbeb-7c3e2d932f49)

**Comment by lpadumorvan** [comment]
Hi

I have the same problem, I did a workaround (or not !).

Can you tell me if the configured height threshold is taken into account during detection ?

DV

```
select:
  - platform: seeed_mr60fda2
    install_height:
      name: "Set Install Height"
#    height_threshold:
#      name: "Set Height Threshold"
    sensitivity:
      name: "Set Sensitivity"
#workaround
  - platform: template
    name: "Set Height Threshold"
    id: height_threshold_select
    options:
      - "0.0m"
      - "0.1m"
      - "0.2m"
      - "0.3m"
      - "0.4m"
      - "0.5m"
      - "0.6m"
    initial_option: "0.4m"
    optimistic: true
    on_value:
      then:
        - lambda: |-
            float h = atof(x.c_str());
            id(my_seeed_mr60fda2).set_height_threshold(h);
```
